version = 0.1
[default.deploy.parameters]
stack_name = "quarkus-tickets-eneida"
resolve_s3 = true
s3_prefix = "quarkus-tickets-eneida"
region = "us-east-1"
profile = "egonzales-cirrus-dev"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
